server:
  port: 8085

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssm_db
#    username: root
#    password: 123456
#
#
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb1_
  configuration:
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

